apiVersion: apps/v1
kind: Deployment
metadata:
  name: dongtai-doc-v3
  namespace: dongtai
  annotations:
    kubesphere.io/description: dongtai-doc-v3
  labels:
    app: dongtai-doc-v3
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dongtai-doc-v3
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/interceptionMode: "TPROXY"
      labels:
        app: dongtai-doc-v3
        version: v1
    spec:
      containers:
        - name: dongtai-doc-v3-container
          image: dongtai/dongtai-doc-v3:VERSION
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "500m"
              memory: 500Mi
            requests:
              cpu: "500m"
              memory: 500Mi
     
