name: Deploy Dongtai Docs

on:
  release:
    types: ["created"]
  push:
    branches: ["main"]

jobs:
  deploy-docs:
    name: "Deploy Dongtai Docs"
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.DOCS_NETLIFY_BUILD_HOOK }}
